### ISSUE TITLE
Implement Contexts

### ISSUE THREAD

**Issue by mwatts15** [openworm/PyOpenWorm#333]
# Summary
Retroactively adding a card for this.

Contexts are, essentially, containers for statements made in PyOpenWorm. Ultimately, they are identified with RDF contexts. The dataset semantics wherein a context is aligned with a named graph are also at play.

Importing a Python module will import a context. Modules can contain all the information for a single context, but contexts can also be defined within modules. Within a module, any defined context would necessarily import the containing context.

Objects are assigned a context when they are first created. Statements about the object are in the context of the object. A 'view' on an imported object can be created in an importing context to make statements about it.

Several contexts may be defined PyOpenWorm, including an 'RDF' and 'RDFS' context which contains definitions from the respective specifications

# TODO
- [X] Define separate contexts for each data source / translator in `insert_worm.py`.
- [x] Update data_sources.rst to reflect addition of translators
- [x] Replace `yarom_import` and `Context::load` with Python import machinery where appropriate
- [ ] Add subclass relationships to the RDF graph
- [ ] Add tests for when the default (un-named) context should be used
- [x] Make it possible to exclude imported contexts when saving contexts
- [ ] Refactor `get_most_specific_type` to not rely on types already in memory -- should rely on the subclass relationships . This is necessitated by the flexibility of the relocation of tracking the class hierarchy into contexts. It might be easier to keep closer to the old behavior, but ultimately `most_specific_type` should be based on the source graph.

**Comment by mwatts15** [comment]
Created new cards for the remaining subtasks here. Closing since Contexts are implemented.
